name: check/azure

on:
  pull_request:
    branches:
      - "*"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1


    - name: Terraform Init
      run: |
        cd terraform-bootstrap
        terraform init

    - name: Terraform Check
      run: |
        cd terraform-bootstrap
        terraform fmt -check

    - name: Terraform Plan
      run: |
        cd terraform-bootstrap
        terraform plan
